apiVersion: skaffold/v2beta12

kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
  - image: k8s-log-shipper
    docker:
      dockerfile: Dockerfile
    sync:
      auto: true
deploy:
  statusCheckDeadlineSeconds: 100
  helm:
    flags:
      upgrade:
        - --install
        - --wait
        - --atomic
        - --history-max=3
    releases:
      - name: k8s-log-shipper
        createNamespace: true
        chartPath: helm
        upgradeOnChange: true
        namespace: monitoring
        valuesFiles:
          - helm/values.develop.yaml
        artifactOverrides:
          image: k8s-log-shipper