apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  {{ .Release.Name }}
  name:  {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app:  {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}
    spec:
      volumes:
        - secret:
            secretName:  ssh-private-key
            defaultMode: 0400
          name: ssh-private-key
#      initContainers:
#      - name: init
#        image: alpine
#        command:
#          - chmod
#          - go-rwx
#          - /root/.ssh/id_rsa
#        volumeMounts:
#          - mountPath:  /root/.ssh
#            name: ssh-private-key
      containers:
      - image:  {{ .Values.image }}
        imagePullPolicy: Always
        env:
          - name: login
            valueFrom:
              secretKeyRef:
                name: wp-log-shipper
                key: login
          - name: logs
            valueFrom:
              secretKeyRef:
                name: wp-log-shipper
                key: logs
          - name: port
            valueFrom:
              secretKeyRef:
                name: wp-log-shipper
                key: port
        name: {{ .Release.Name }}
        command:  ["ssh"]
        args: ["-i", "/root/.ssh/id_rsa", "-p", "$(port)","-o","StrictHostKeyChecking=no", "$(login)", "tail", "-f", "$(logs)"]
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath:  /root/.ssh
            name: ssh-private-key
      imagePullSecrets:
        - name: itlancer

